package Account;

import Query.QueryData;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * AnalystInternalFrame.java - for users with analyst permissions. Displays three
 * tables for vehicle inventory, and incident data
 * CSIS 643 - D01
 * @author Kore Woody
 */
public class AnalystInternalFrame extends javax.swing.JInternalFrame {

    public String nameofAnalyst;
    public static String name,firstName,lastName,department,userID,table;
    public static boolean isAdmin,isManager,isEngineer,isAnalyst,isTech;
    
    /**
     * Creates new form AnalystInternalFrame
     * @param userID
     * @param department
     * @param name
     * @param isEngineer
     * @param lastName
     * @param firstName
     * @param isAnalyst
     * @param isAdmin
     * @param isTech
     * @param isManager
     * @param table
     */
    public AnalystInternalFrame(String userID, String name, 
            String firstName, String lastName, String department, 
            boolean isAdmin, boolean isManager, boolean isEngineer, 
            boolean isAnalyst, boolean isTech, String table) {
        super("",true,false,true);
        initComponents();
        
        // set user values
        nameofAnalyst = name;
        this.userID = userID;
        this.name = name;
        this.firstName = firstName;
        this.lastName = lastName;
        this.department = department;
        this.isAdmin = isAdmin;
        this.isManager = isManager;
        this.isEngineer = isEngineer;
        this.isAnalyst = isAnalyst;
        this.isTech = isTech;
        
        initComponents();
        // set title
        setTitle(table);
        this.table = table;
        
        //update table model
        refresh();
        
        this.pack();
        this.rootPaneCheckingEnabled = true;   
    }// end AnalystInternalFrame constructor

    /**
     * refresh method updates table based on its title
     */
    public void refresh()
    {
        //
        QueryData qd = new QueryData();

        if (table.matches("VehicleInventory"))
        {
            qd.selectVehicles();
        }
        if(table.matches("VehicleDeaths"))
        {
            qd.selectDeaths();
        }
        if (table.matches("SuddenAcceleration"))
        {
            qd.selectSuddenAcceleration();
        }
        DefaultTableModel model = qd.getModel();
        if (model!=null)
        {
            // update table model
            tblAnalyst.setAutoCreateRowSorter(true);
            tblAnalyst.setModel(model);
            tblAnalyst.repaint();
            tblAnalyst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblAnalyst.getSelectionModel().addListSelectionListener(this.tblAnalyst);
        }
    }// end refresh method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalyst = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblAnalyst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnalyst);

        jMenu1.setText("File");
        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnalyst;
    // End of variables declaration                   
}// end AnalystInternalFrame class
