package Account;

import Chronology.TimeOut;
import Query.Query;
import Query.QueryAccount;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Timer;

/**
 * LoginFrame.java - Main startup form used to authenticate user and display 
 * Application window
 * CSIS 643 - D01
 * @author Kore Woody
 */
public class LoginFrame extends JFrame
{

    /**
     * Creates new form LoginWindow
     */
    public LoginFrame() {
        initComponents();
        //intitialize new query and setup encryption key
        Query q = new Query();
        q.startup();
    }// end Login constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnForgotPassword = new javax.swing.JButton();
        txtPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1750, 750));
        setResizable(false);

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnForgotPassword.setText("Forgot Password");
        btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordActionPerformed(evt);
            }
        });

        txtPasswordField.setText("password");
        txtPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnForgotPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtPasswordField))))
                .addGap(50, 50, 50))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnForgotPassword))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * btnLoginAction button method calls login method.
     * @param evt Login button pressed
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         

        Login();
    }                                        
    // end btnLoginAction method
    
    /**
     * Login method when login button is pressed. Queries database and verifies
     * credentials
     */
    public void Login() 
    {
        // get username and passowrd
        String userID = txtID.getText();
        char[] password = txtPasswordField.getPassword();
        String passID = "";
        // convert passsord characters to string
        for (char c : password) {
            passID = passID + c;
        }
        //Instantialize new QueryAccount method
        QueryAccount qa = new QueryAccount();
        boolean valid = qa.Login(userID, passID);// validate user
        // check user validation
        if (valid == false) // invalid
        { 
            // show error dialog
            JOptionPane.showMessageDialog(this, "Invalid Login");

        } 
        else // valid results 
        { 
            // get user profile data
            String type = qa.getType();
            String name = qa.getName();
            String firstName = qa.getFirstName();
            String lastName = qa.getLastName();
            String department = qa.getDepartment();
            boolean isAdmin = qa.getIsAdmin();
            boolean isManager = qa.getIsManager();
            boolean isEngineer = qa.getIsEngineer();
            boolean isAnalyst = qa.getIsAnalyst();
            boolean isTech = qa.getIsTech();

            // Evaluate the type of the user
            if (type.matches("Admin") || type.matches("Manager")
                    || type.matches("Engineer") || type.matches("Engineer")
                    || type.matches("Analyst") || type.matches("Tech")) {
                
                // sent desktop dimensions for ERPMainWindow
                Dimension desktopSize = Toolkit.getDefaultToolkit().getScreenSize();
                int width = desktopSize.width;
                int height = desktopSize.height;
                int x = width / 5;
                int y = height / 5;
                int fwidth = (int) (width * 0.5963541667);
                int fheight = height / 2;

                // Initialize new ERP Main Window
                JFrame frame = new ERPMainWindow(
                        userID, name, firstName, lastName, type, department,
                        isAdmin, isManager, isEngineer, isAnalyst, isTech,
                        x, y, fwidth, fheight, desktopSize);
                frame.setBounds(x, y, fwidth, fheight);
                frame.setVisible(true);
                setVisible(false);
                dispose();

                //Initialize new Thread object for ERP Window
                Thread thread = new Thread(new ERPMainWindow(
                        userID, name, firstName, lastName, type, department,
                        isAdmin, isManager, isEngineer, isAnalyst, isTech,
                        x, y, fwidth, fheight, desktopSize));
                // start thread
                thread.start();
                // initialize 
                Timer timer = new Timer();
                TimeOut timeout = new TimeOut(thread, timer);
                timer.schedule(timeout, 100);
                timeout.run();

            } 
            else // invalid account type
            {
                // display error message
                JOptionPane.showMessageDialog(this, "Login Error");
            }
        }
    }// end Login method
    
    /**
     * btnForgotPasswordActionPerformed method
     * @param evt 
     */
    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        JFrame frmForgotPassword = new ForgotPasswordFrame();
        frmForgotPassword.setBounds(this.getX(), this.getY(), 300, 200);
        frmForgotPassword.setVisible(true);
    }                                                 
    // end btnForgotPasswordActionPerformed method
    
    /**
     * txtIDKeyPressed method 
     * @param evt 
     */
    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
        int key = evt.getKeyCode(); // get key value
        
        if (key==java.awt.event.KeyEvent.VK_ENTER) // key is enter
        {
            txtPasswordField.requestFocus();// set focus to password
        }
    }                                
    // end txtIDKeyPressed method
    
    /**
     * txtPasswordFieldKeyPressed method
     * @param evt 
     */
    private void txtPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {                                            
        int key = evt.getKeyCode(); // get key value

        if (key==java.awt.event.KeyEvent.VK_ENTER) // key is enter
        {
            btnLogin.doClick();// click button
        }
    }                                           
    // end txtPasswordFieldKeyPressed method
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }// end main method

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPasswordField;
    // End of variables declaration                   

}// end LoginFrame
