package Admin;

import Query.Query;
import Query.QueryAccount;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 * ApplicationSettingsFrame.java - frame enables admin users an interface to change
 * application time out and the encryption key
 * CSIS 643 - D01
 * @author Kore Woody
 */
public class ApplicationSettingsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationSettingsFrame
     */
    public ApplicationSettingsFrame() {
        initComponents();
        
        QueryAccount qa = new QueryAccount();
        ResultSet rs = qa.selectAccountSettings();
        cmbHours.setSelectedItem(qa.getHours());
        cmbMinutes.setSelectedItem(qa.getMinutes());
        cmbSeconds.setSelectedItem(qa.getSeconds());
        
    }// end ApplicationSettingsFrame constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tbApplicationSettings = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbMinutes = new javax.swing.JComboBox<>();
        cmbSeconds = new javax.swing.JComboBox<>();
        cmbHours = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateTimeOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtEncryptionKey = new javax.swing.JPasswordField();
        btnUpdateKey = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Application Time Out");

        cmbMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        cmbSeconds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        cmbHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08" }));

        jLabel1.setText("Hours");

        jLabel2.setText("Minutes");

        jLabel3.setText("Seconds");

        btnUpdateTimeOut.setText("Update");
        btnUpdateTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTimeOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmbSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdateTimeOut))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnUpdateTimeOut)
                .addContainerGap())
        );

        tbApplicationSettings.addTab("Time Out", jPanel1);

        txtEncryptionKey.setText("jPasswordField1");

        btnUpdateKey.setText("Update");
        btnUpdateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKeyActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter new encryption key");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEncryptionKey)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateKey))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEncryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnUpdateKey)
                .addContainerGap())
        );

        tbApplicationSettings.addTab("Encryption", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbApplicationSettings)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbApplicationSettings)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * btnUpdateTimeOutActionPerformed update timeout button action listener
     * @param evt 
     */
    private void btnUpdateTimeOutActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String hours = cmbHours.getSelectedItem().toString();
        String minutes = cmbMinutes.getSelectedItem().toString();
        String seconds = cmbSeconds.getSelectedItem().toString();
        
        // instantiate new QueryAccount object
        QueryAccount qa = new QueryAccount();
        // update time out limit
        qa.updateAppSettings(hours, minutes, seconds);
        // show update message
        JOptionPane.showMessageDialog(rootPane, "Update Complete");
    }                                                
    //end btnUpdateTimeOutActionPerformed method
    
    /**
     * btnUpdateKeyActionPerformed update encryption key button action listener
     * @param evt 
     */
    private void btnUpdateKeyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // get new key
        char[] newKey = txtEncryptionKey.getPassword();
        //check for lengh
        if (newKey.length>=16)
        {
            // convert char key array to string
            String key = "";
            for (char c : newKey) {
                key = key + c;
            }
            // instantiate new Query object
            Query q = new Query();
            // change encryption key
            q.changeEncryptionKey(key);
            // show update message
            JOptionPane.showMessageDialog(rootPane, "Update Complete");
        }
        else // key less then requirement
        {
            JOptionPane.showMessageDialog(this, "New key must be at least 16 characters long.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
        }
    }                                            
    //end btnUpdateKeyActionPerformed method

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnUpdateKey;
    private javax.swing.JButton btnUpdateTimeOut;
    private javax.swing.JComboBox<String> cmbHours;
    private javax.swing.JComboBox<String> cmbMinutes;
    private javax.swing.JComboBox<String> cmbSeconds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tbApplicationSettings;
    private javax.swing.JPasswordField txtEncryptionKey;
    // End of variables declaration                   
}// end ApplicationSettingsFrame class
