package Chronology;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;

/**
 * CalendarInternalFrame.java - frame used by all user account types. displays
 * the calendar month and indicated the current date
 * CSIS 643 - D01
 * @author Kore Woody
 */
public class CalendarInternalFrame extends JInternalFrame {

    public String title = "";
    
    /**
     * Creates new form CalendarInternalFrame
     */
    public CalendarInternalFrame() {
        //super("",true,true,true);
        initComponents();
                
        // instantiate new Chronology object
        Chronology c = new Chronology(); 
        // set title as current date
        setTitle("Calendar: " + c.getDate());
        
        // get calendar table attributes
        int row = c.getWeekOfMonth();
        int column = c.getDayOfWeek();
        int d = c.getDayOfMonth();
                
        // set calendar model
        c.setCalendar();
        
        // get and update calendar table model
        tblCalendar.setModel(c.getCalendar());
        // select current date
        tblCalendar.changeSelection(row, column-1, false, false);
        // add * to indicate current date
        tblCalendar.setValueAt(d+"*", row, column-1);
        tblCalendar.repaint();
        this.pack();
    }// end constructor    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalendar = new javax.swing.JTable();

        tblCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", "31", null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Su", "M", "Tu", "W", "Th", "F", "S"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCalendar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCalendar.setColumnSelectionAllowed(false);
        tblCalendar.setEnabled(false);
        tblCalendar.setRowHeight(25);
        tblCalendar.setRowSelectionAllowed(false);
        tblCalendar.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblCalendar.setShowGrid(true);
        jScrollPane1.setViewportView(tblCalendar);
        tblCalendar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCalendar;
    // End of variables declaration                   
}// end CalendarInternalFrame class
