package Admin;

import Account.AdminInternalFrame;
import Chronology.Chronology;
import Query.QueryAccount;
import javax.swing.JOptionPane;

/**
 * UserAccountFrame.java - frame displays user account information. Used for 
 * creating and editing accounts
 * CSIS 643 - D01
 * @author Kore Woody
 */
public class UserAccountFrame extends javax.swing.JFrame {

    String empID;
    String passID;
    String defaultPassID;
    
    /**
     * Creates new form editUserAccountFrame
     * @param empID
     */
    public UserAccountFrame(String empID) {
        initComponents();
        this.empID = empID;
        // instantiate new QueryAccount object
        QueryAccount qa = new QueryAccount();
        
        // check fro null id input
        if (empID!=null)// existing account
        {
            btnCreateUser.setVisible(false);
            btnCreateUser.setEnabled(false);
            
            qa.setUserProfile(empID);
            
            String createdDate = qa.getDateCreated();
            
            txtDate.setText(createdDate);
            txtFirstName.setText(qa.getFirstName());
            txtLastName.setText(qa.getLastName());
            txtUserName.setText(empID);
            txtPassword.setText(qa.getPassID());
            
            
            String department = qa.getDepartment();
            String type = qa.getType();
            
            cmbType.setSelectedItem(type);
            cmbDepartment.setSelectedItem(department);
            
            boolean isAdmin = qa.getIsAdmin();
            boolean isManager = qa.getIsManager();
            boolean isEngineer = qa.getIsEngineer();
            boolean isAnalyst = qa.getIsAnalyst();
            boolean isTech = qa.getIsTech();
            
            if (isAdmin==true)
            {
                cbAdmin.doClick();
            }
            if (isManager==true)
            {
                cbManager.doClick();
            }
            if (isEngineer==true)
            {
                cbEngineer.doClick();
            }
            if (isAnalyst==true)
            {
                cbAnalyst.doClick();
            }
            if (isTech==true)
            {
                cbTech.doClick();
            }
        }
        else// new account
        {
            // set button viisibity
            btnDeleteUser.setVisible(false);
            btnUpdateUser.setVisible(false);
            btnDeleteUser.setEnabled(false);
            btnUpdateUser.setEnabled(false);
            // instantiate new Chronology object 
            Chronology c = new Chronology();
            // set date feld with current date then lock text field
            txtDate.setText(c.getDate());
            txtDate.setEditable(false);
            this.defaultPassID = qa.getDefaultPassID();// set default password
        }
        // lock user name
        txtUserName.setEditable(false);
    }// end UserAccountFrame constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUserAccountMain = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        btnGenerateUserName = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnDefaultPassowrd = new javax.swing.JButton();
        cmbDepartment = new javax.swing.JComboBox<>();
        lblDepartment = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        pnlPrivileges = new javax.swing.JPanel();
        cbAdmin = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbManager = new javax.swing.JCheckBox();
        cbEngineer = new javax.swing.JCheckBox();
        cbAnalyst = new javax.swing.JCheckBox();
        cbTech = new javax.swing.JCheckBox();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        tbtnCustomDate = new javax.swing.JToggleButton();
        btnDeleteUser = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(1000, 1000));

        pnlUserAccountMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLastName.setText("Last Name");

        lblFirstName.setText("First Name");

        lblUserName.setText("User Name");

        btnGenerateUserName.setText("Generate");
        btnGenerateUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateUserNameActionPerformed(evt);
            }
        });

        lblPassword.setText("Password");

        txtPassword.setText("password");

        btnDefaultPassowrd.setText("Generate");
        btnDefaultPassowrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultPassowrdActionPerformed(evt);
            }
        });

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department...", "General", "Analyst", "Engineering", "Software", "Hardware", "Electrical", "Tech Support" }));

        lblDepartment.setText("Department");

        lblType.setText("Type");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type...", "Admin", "Manager", "Engineer", "Analyst", "Tech" }));

        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        cbAdmin.setText("Admin");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Account Privileges");

        cbManager.setText("Manager");

        cbEngineer.setText("Engineer");

        cbAnalyst.setText("Analyst");

        cbTech.setText("Tech");

        javax.swing.GroupLayout pnlPrivilegesLayout = new javax.swing.GroupLayout(pnlPrivileges);
        pnlPrivileges.setLayout(pnlPrivilegesLayout);
        pnlPrivilegesLayout.setHorizontalGroup(
            pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                        .addGroup(pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(cbEngineer))
                            .addComponent(cbAdmin)
                            .addComponent(cbManager))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTech)
                            .addComponent(cbAnalyst))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrivilegesLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlPrivilegesLayout.setVerticalGroup(
            pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                        .addComponent(cbAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbManager)
                        .addGap(9, 9, 9)
                        .addComponent(cbEngineer))
                    .addGroup(pnlPrivilegesLayout.createSequentialGroup()
                        .addComponent(cbTech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAnalyst)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblDate.setText("Date");

        tbtnCustomDate.setText("Custom Date");
        tbtnCustomDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnCustomDateActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserAccountMainLayout = new javax.swing.GroupLayout(pnlUserAccountMain);
        pnlUserAccountMain.setLayout(pnlUserAccountMainLayout);
        pnlUserAccountMainLayout.setHorizontalGroup(
            pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlPrivileges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUserAccountMainLayout.createSequentialGroup()
                                .addComponent(lblDepartment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUserAccountMainLayout.createSequentialGroup()
                                .addComponent(lblType)
                                .addGap(50, 50, 50)
                                .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUserAccountMainLayout.createSequentialGroup()
                                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName)
                                    .addComponent(txtFirstName)))))
                    .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txtDate))
                    .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(txtPassword))
                    .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDate)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserAccountMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserAccountMainLayout.createSequentialGroup()
                                .addComponent(btnDeleteUser)
                                .addGap(34, 34, 34)
                                .addComponent(btnCreateUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnUpdateUser))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserAccountMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbtnCustomDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDefaultPassowrd, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerateUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                                .addComponent(lblUserName)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserName)))))
                .addContainerGap())
        );
        pnlUserAccountMainLayout.setVerticalGroup(
            pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserAccountMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbtnCustomDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment))
                .addGap(18, 18, 18)
                .addComponent(pnlPrivileges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerateUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDefaultPassowrd)
                .addGap(24, 24, 24)
                .addGroup(pnlUserAccountMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnCreateUser))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUserAccountMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUserAccountMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * btnGenerateUserNameActionPerformed generate username button listener
     * @param evt 
     */
    private void btnGenerateUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateUserNameActionPerformed
        // get first and last name
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        // check for null values
        if (!firstName.matches("")&&firstName!=null&&!lastName.matches("")&&lastName!=null)
        {
            // Generate new username
            char firstLetter = firstName.charAt(0);
            // combine first leter of first name and last name
            String newUserID = firstLetter + lastName.toLowerCase();
            newUserID = newUserID.toLowerCase();// set to lowercase
            
            //instantiate new QueryAccount object
            QueryAccount qa = new QueryAccount();
            // validate new username
            qa.matchProfile(newUserID, firstName, lastName);
            // get validated userId
            newUserID = qa.getNewUserID();
            txtUserName.setText(newUserID);// display
        }
    }//GEN-LAST:event_btnGenerateUserNameActionPerformed
    // end btnGenerateUserNameActionPerformed method
    
    /**
     * btnDefaultPassowrdActionPerformed generate default password button
     * listener
     * @param evt 
     */
    private void btnDefaultPassowrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultPassowrdActionPerformed
        // instantiate new QueryAccount object
        QueryAccount qa = new QueryAccount();
        String defaultPass = qa.getDefaultPassID();// get default passowrd
        if (defaultPass.matches(""))//check for null
        {
            defaultPass = "password";
        }
        txtPassword.setText(defaultPass);// set defautl passsword text
    }//GEN-LAST:event_btnDefaultPassowrdActionPerformed
    // end btnDefaultPassowrdActionPerformed
    
    /**
     * btnCreateUserActionPerformed create button listener 
     * @param evt 
     */
    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // get profile attroibutes
        String date = txtDate.getText();
        String userID = txtUserName.getText();
        String passID = txtPassword.getText();
        String type = cmbType.getSelectedItem().toString();
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String name = firstName + " " + lastName;
        String department = cmbDepartment.getSelectedItem().toString();
        boolean isAdmin = false;
        boolean isManager = false;
        boolean isEngineer = false;
        boolean isAnalyst = false;
        boolean isTech = false;
        
        // get profile permissions
        if (cbAdmin.isSelected()) {
            isAdmin = true;
        }
        if (cbManager.isSelected()) {
            isManager = true;
        }
        if (cbEngineer.isSelected()) {
            isEngineer = true;
        }
        if (cbAnalyst.isSelected()) {
            isAnalyst = true;;
        }
        if (cbTech.isSelected()) {
            isTech = true;
        }
            
        QueryAccount qa = new QueryAccount();
        boolean accountCreated = qa.createUserAccount(date, userID, passID, type, name, firstName, lastName, department, isAdmin, isManager, isEngineer, isAnalyst, isTech);
        if (accountCreated==true)
        {
            // Show message
            JOptionPane.showMessageDialog(this, "Account created.", "Successful ", JOptionPane.OK_OPTION);
            //Dispose
            this.dispose();
        }
        else
        {
            // Show message with error, dont dispose
            JOptionPane.showMessageDialog(this, "Account not created.", "Error ", JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btnCreateUserActionPerformed
    // end btnCreateUserActionPerformed method
    
    /**
     * btnUpdateUserActionPerformed update button listener
     * @param evt 
     */
    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
       // get profile attributes
        String date = txtDate.getText();
        String userID = txtUserName.getText();
        String passID = txtPassword.getText();
        String type = cmbType.getSelectedItem().toString();
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String name = firstName + " " + lastName;
        String department = cmbDepartment.getSelectedItem().toString();
        boolean isAdmin = false;
        boolean isManager = false;
        boolean isEngineer = false;
        boolean isAnalyst = false;
        boolean isTech = false;
        
        // get profile permissions
        if (cbAdmin.isSelected()) {
            isAdmin = true;
        }
        if (cbManager.isSelected()) {
            isManager = true;
        }
        if (cbEngineer.isSelected()) {
            isEngineer = true;
        }
        if (cbAnalyst.isSelected()) {
            isAnalyst = true;;
        }
        if (cbTech.isSelected()) {
            isTech = true;
        }
        
        //Instantiate new QueryAccount Object
        QueryAccount qa = new QueryAccount();
        // update account
        boolean accountUpdated = qa.updateUserAccount(date, userID, passID, type, name, firstName, lastName, department, isAdmin, isManager, isEngineer, isAnalyst, isTech);
        if (accountUpdated==true)
        {
            // Show message
            JOptionPane.showMessageDialog(this, "Account updated.", "Sucessful ", JOptionPane.OK_OPTION);
            //Dispose
            this.dispose();
        }
        else
        {
            // Show message with error, dont dispose
            JOptionPane.showMessageDialog(this, "Account not updated.", "Error ", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnUpdateUserActionPerformed
    // end btnUpdateUserActionPerformed method
    
    /**
     * btnDeleteUserActionPerformed delete button listener
     * @param evt 
     */
    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        
        String userID = txtUserName.getText();
            
        QueryAccount qa = new QueryAccount();
        boolean accountDeleted = qa.deleteUserAccount(userID);
        
        if (accountDeleted==true)
        {
            // Show message
            JOptionPane.showMessageDialog(this, "Account deleted.", "Sucessful ", JOptionPane.OK_OPTION);
            //Dispose
            this.dispose();
        }
        else
        {
            // Show message with error, dont dispose
            JOptionPane.showMessageDialog(this, "Account not deleted.", "Error ", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed
    // end btnDeleteUserActionPerformed method
    
    /**
     * tbtnCustomDateActionPerformed toggle listener sets the custom date as
     * enabled or disabled
     * @param evt 
     */
    private void tbtnCustomDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCustomDateActionPerformed
        if (tbtnCustomDate.isSelected())// if selected
        {
            txtDate.setEditable(true);
            
        }
        else// not selected
        {
            txtDate.setEditable(false);
        }
    }//GEN-LAST:event_tbtnCustomDateActionPerformed
    // end tbtnCustomDateActionPerformed method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDefaultPassowrd;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnGenerateUserName;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JCheckBox cbAdmin;
    private javax.swing.JCheckBox cbAnalyst;
    private javax.swing.JCheckBox cbEngineer;
    private javax.swing.JCheckBox cbManager;
    private javax.swing.JCheckBox cbTech;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlPrivileges;
    private javax.swing.JPanel pnlUserAccountMain;
    private javax.swing.JToggleButton tbtnCustomDate;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}// end UserAccountFrame class
