package Ticket;

import Query.QueryTicket;
import javax.swing.JOptionPane;

/**
 * TicketLockFrame.java - frame for setting the lock status of tickets based on
 * number entered
 * CSIS 643 - D01
 * @author NoFac3
 */
public class TicketLockFrame extends javax.swing.JFrame {

    String ticketNumber;
    /**
     * Creates new form TicketLockFrame
     */
    public TicketLockFrame() {
        initComponents();
    }// end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnlock = new javax.swing.JButton();
        txtTicketNumber = new javax.swing.JTextField();
        lblSearchTicket = new javax.swing.JLabel();
        lblSearchTicket1 = new javax.swing.JLabel();
        btnLock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnUnlock.setText("UnLock");
        btnUnlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlockActionPerformed(evt);
            }
        });

        lblSearchTicket.setText("Enter Ticket Number(s)");

        lblSearchTicket1.setText("For multiple entries, separate ticket numbers with a space");

        btnLock.setText("Lock");
        btnLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblSearchTicket))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblSearchTicket1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtTicketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnUnlock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLock)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblSearchTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearchTicket1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTicketNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnlock)
                    .addComponent(btnLock))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * btnUnlockActionPerformed
     * @param evt 
     */
    private void btnUnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlockActionPerformed
        // check for null input
        if (!txtTicketNumber.getText().isEmpty())
        {
        String[] tickets = txtTicketNumber.getText().split(" ");
        QueryTicket qt = new QueryTicket();
        for (String ticket: tickets)
        {
            qt.setTicketLock(ticket.trim(), false);
            this.setVisible(false);
            this.dispose();
        }
        }
        else// null entry
        {
            JOptionPane.showMessageDialog(this, "Invalid entry for Ticket Number(s)");
        }

    }//GEN-LAST:event_btnUnlockActionPerformed
    // end btnUnlockActionPerformed method
    
    /**
     * btnLockActionPerformed lock button listener for locking tickets
     * @param evt lock button selected
     */
    private void btnLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockActionPerformed
        // check for null ticket number entry
        if (!txtTicketNumber.getText().isEmpty())
        {
            // get ticket numbers and split by space
            String[] tickets = txtTicketNumber.getText().split(" ");
            // instantiate new QueryTicket object
            QueryTicket qt = new QueryTicket();
            // update entered tickets
            for (String ticket: tickets)
            {
                qt.setTicketLock(ticket.trim(), true);                
            }
            // close frame
            this.setVisible(false);
            this.dispose();
        }
        else// null entry
        {
            JOptionPane.showMessageDialog(this, "Invalid entry for Ticket Number(s)");
        }
    }//GEN-LAST:event_btnLockActionPerformed
    //end btnLockActionPerformed method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLock;
    private javax.swing.JButton btnUnlock;
    private javax.swing.JLabel lblSearchTicket;
    private javax.swing.JLabel lblSearchTicket1;
    private javax.swing.JTextField txtTicketNumber;
    // End of variables declaration//GEN-END:variables
}// end TicketLockFrame class
