package Ticket;

import Query.QueryData;
import Ticket.TicketFrame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * VehicleDialog.java - dialog for querying vehicle information to add to tickets
 * CSIS 643 - D01
 * @author Kore Woody
*/
public class VehicleDialog extends JDialog {

    private String vmodel,year,vin;

    /**
     * Creates new form VehicleFrame
     * @param parent
     * @param title
     * @param modal
     */
    public VehicleDialog(java.awt.Frame parent, boolean modal,String title) {
        super(parent, modal);
        initComponents();
        setTitle(title + " Vehicle");
        
        // check for new ticket
        if (title.matches("New"))// new ticket
        {
            btnUpdate.setVisible(false);
        }
        else// existing vehicle
        {
            btnAdd.setVisible(false);
        }
        
        // instantiate new QueryData object
        QueryData qd = new QueryData();
        // query and set vehicles table model
        qd.selectVehicles();
        DefaultTableModel model = qd.getModel();
        
        if (model!=null)
        {
            // update table model
            tblNewVehicle.setAutoCreateRowSorter(true);
            tblNewVehicle.setModel(model);
            tblNewVehicle.repaint();
            tblNewVehicle.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblNewVehicle.getSelectionModel().addListSelectionListener(this.tblNewVehicle);
        }

    }// end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtVIN = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNewVehicle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("VIN");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");

        tblNewVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNewVehicle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addComponent(txtVIN)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * btnAddActionPerformed add button listener for adding vehicle to customer 
     * database
     * @param evt add button click
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // get row selected
        int row = tblNewVehicle.getSelectedRow();
        // get and set VIN
        String vin = txtVIN.getText();
        this.vin = vin;
        
        // check for selected row
        if (row!=-1)
        {
            // check for null VIN input
            if ((vin!=null && !vin.matches("")))
            {
                // get and set year and model from selected table row
                String year = tblNewVehicle.getModel().getValueAt(row, 0).toString();
                String model = tblNewVehicle.getModel().getValueAt(row, 1).toString();
                this.year = year;
                this.vmodel = model;
                // instantiate new QueryData object
                QueryData qd = new QueryData();
                // set customer vehicle
                qd.setCustomerVehicle(year, model, vin);
                // set ticket input values
                TicketFrame.cmbYear.setSelectedItem(year);
                TicketFrame.cmbModel.setSelectedItem(model);
                TicketFrame.txtVin.setText(vin);
                // close frame
                this.setVisible(false);
                this.dispose();
            }
            else// no row selected
            {
                JOptionPane.showMessageDialog(this, "Select a row from the table.");
            }
        }
        else// null vin input
        {
            JOptionPane.showMessageDialog(this, "VIN cannot be null.");
        }
    }//GEN-LAST:event_btnAddActionPerformed
    // end btnAddActionPerformed method
    
   // end btnRemoveActionPerformed method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNewVehicle;
    public javax.swing.JTextField txtVIN;
    // End of variables declaration//GEN-END:variables
}// end VehicleDialog class
